export { default as Home } from './Home';
export { default as Shop } from './Shop';
export { default as Product, loader as productLoader } from './Product';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as Cart } from './Cart';
export { default as Checkout } from './Checkout';
export { default as Search } from './Search';
export { default as Wishlist } from './Wishlist';
export { default as ProductTag } from './ProductTag';
export { default as Brand } from './Brand';
export { default as MyAccount } from './MyAccount';
export { default as Blogs } from './Blogs';
export { default as BlogDetail } from './BlogDetail';
export { default as NotFound404 } from './404';
